import os
from dotenv import load_dotenv
load_dotenv()

#CORREÇÃO PARA O ARQUIVO CARREGAR IMAGEM CORRETAMENTE(BY FELIPE ANDRADE, DEPOIS DE MUITO TENTAR)
connection_string = os.getenv('AZURE_STORAGE_CONNECTION_STRING')
ENDPOINT = os.getenv('ENDPOINT')
KEY = os.getenv('SUBSCRIPTION_KEY')
AZURE_STORAGE_CONNECTION_STRING = os.getenv('STORAGE_CONNECTION_STRING')
CONTAINER_NAME = os.getenv('CONTAINER_NAME')

#VERSÃO DO PROFESSOR NÃO TINHA AS INFORMAÇÕES FORA DA CLASSE E FUNCIONAVA, QUE É A PARTE ABAIXO.
#NA MINHA VERSÃO SÓ FUNCIONOU INCLUINDO AS MESMAS INFORMÇÕES DENTRO E FORA E DA CLASSE.

class Config:
    ENDPOINT = os.getenv('ENDPOINT')
    KEY = os.getenv('SUBSCRIPTION_KEY')
    AZURE_STORAGE_CONNECTION_STRING = os.getenv('STORAGE_CONNECTION_STRING')
    CONTAINER_NAME = os.getenv('CONTAINER_NAME')